# TCL File Generated by Component Editor 12.1
# Tue Oct 08 09:49:26 CEST 2013
# DO NOT MODIFY


# 
# AUDIO_DAC_FIFO "AUDIO_DAC_FIFO" v1.0
# null 2013.10.08.09:49:26
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module AUDIO_DAC_FIFO
# 
set_module_property NAME AUDIO_DAC_FIFO
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME AUDIO_DAC_FIFO
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AUDIO_DAC_FIFO
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file AUDIO_DAC_FIFO.v VERILOG PATH AUDIO_DAC_FIFO.v
add_fileset_file FIFO_16_256.v VERILOG PATH FIFO_16_256.v


# 
# parameters
# 
add_parameter REF_CLK INTEGER 18432000 ""
set_parameter_property REF_CLK DEFAULT_VALUE 18432000
set_parameter_property REF_CLK DISPLAY_NAME REF_CLK
set_parameter_property REF_CLK TYPE INTEGER
set_parameter_property REF_CLK UNITS None
set_parameter_property REF_CLK ALLOWED_RANGES -2147483648:2147483647
set_parameter_property REF_CLK DESCRIPTION ""
set_parameter_property REF_CLK HDL_PARAMETER true
add_parameter SAMPLE_RATE INTEGER 8000
set_parameter_property SAMPLE_RATE DEFAULT_VALUE 8000
set_parameter_property SAMPLE_RATE DISPLAY_NAME SAMPLE_RATE
set_parameter_property SAMPLE_RATE TYPE INTEGER
set_parameter_property SAMPLE_RATE UNITS None
set_parameter_property SAMPLE_RATE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SAMPLE_RATE HDL_PARAMETER true
add_parameter DATA_WIDTH INTEGER 16
set_parameter_property DATA_WIDTH DEFAULT_VALUE 16
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter CHANNEL_NUM INTEGER 2
set_parameter_property CHANNEL_NUM DEFAULT_VALUE 2
set_parameter_property CHANNEL_NUM DISPLAY_NAME CHANNEL_NUM
set_parameter_property CHANNEL_NUM TYPE INTEGER
set_parameter_property CHANNEL_NUM UNITS None
set_parameter_property CHANNEL_NUM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CHANNEL_NUM HDL_PARAMETER true


# 
# display items
# 


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true

add_interface_port s0 avs_s0_writedata writedata Input DATA_WIDTH
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_readdata readdata Output DATA_WIDTH
add_interface_port s0 avs_s0_read read Input 1
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end oAUD_BCK export Output 1
add_interface_port conduit_end oAUD_LRCK export Output 1
add_interface_port conduit_end oAUD_DATA export Output 1
add_interface_port conduit_end oAUD_XCK export Output 1
add_interface_port conduit_end iCLK_18_4 export Input 1

