# TCL File Generated by Component Editor 12.1
# Thu Oct 03 15:51:14 CEST 2013
# DO NOT MODIFY


# 
# SRAM_DE2 "SRAM_DE2" v1.0
# null 2013.10.03.15:51:14
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module SRAM_DE2
# 
set_module_property NAME SRAM_DE2
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME SRAM_DE2
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL SRAM_DE2
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file SRAM_DE2.vhd VHDL PATH SRAM_DE2.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 20
set_interface_property s0 isMemoryDevice true
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitStates 20
set_interface_property s0 readWaitTime 20
set_interface_property s0 setupTime 20
set_interface_property s0 timingUnits Nanoseconds
set_interface_property s0 writeWaitStates 20
set_interface_property s0 writeWaitTime 20
set_interface_property s0 ENABLED true

add_interface_port s0 avs_s0_readdata readdata Output 16
add_interface_port s0 avs_s0_writedata writedata Input 16
add_interface_port s0 avs_s0_address address Input 18
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_byteenable byteenable Input 2
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 1
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end_0
# 
add_interface conduit_end_0 conduit end
set_interface_property conduit_end_0 associatedClock clock
set_interface_property conduit_end_0 associatedReset ""
set_interface_property conduit_end_0 ENABLED true

add_interface_port conduit_end_0 coe_SRAM_ADDR export Output 18
add_interface_port conduit_end_0 coe_SRAM_DQ export Bidir 16
add_interface_port conduit_end_0 coe_SRAM_WE_N export Output 1
add_interface_port conduit_end_0 coe_SRAM_OE_N export Output 1
add_interface_port conduit_end_0 coe_SRAM_UB_N export Output 1
add_interface_port conduit_end_0 coe_SRAM_LB_N export Output 1
add_interface_port conduit_end_0 coe_SRAM_CE_N export Output 1

